language: ruby
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
before_install:
  - gem uninstall -v '>= 2.0.1' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '1.16.6'

script: "bundle exec rake spec"
gemfile:
  - gemfiles/rails_4.2_pc_4_2.gemfile
  - gemfiles/rails_4.2_pc_4_3.gemfile
  - gemfiles/rails_4.2_pc_5_0.gemfile
  - gemfiles/rails_4.2_pc_5_2.gemfile
  - gemfiles/rails_4.2_pc_6_0.gemfile
  - gemfiles/rails_5.0_pc_4_2.gemfile
  - gemfiles/rails_5.0_pc_5_0.gemfile
  - gemfiles/rails_5.0_pc_5_2.gemfile
  - gemfiles/rails_5.0_pc_6_0.gemfile
  - gemfiles/rails_5.1_pc_4_2.gemfile
  - gemfiles/rails_5.1_pc_5_0.gemfile
  - gemfiles/rails_5.1_pc_5_2.gemfile
  - gemfiles/rails_5.1_pc_6_0.gemfile
